### ISSUE TITLE
Shareable Config files for eslint and prettier

### ISSUE THREAD

**Issue by nikzaugg** [kwizapp/kwiz#28]
### Description

In order to now have to maintain config files across all our repositories, it would be nice to have them published in a package that can be extended inside `eslintrc` and `prettierrc`.

### Tasks

- [ ] create new repositories containing the commom configuration files
- [ ] for eslint make sure to include one for typescript and one for javascript
- [ ] decide on a common prettier code style
- [ ] add workflow to create and publish npm package on GPR

### Context 
https://github.com/kwizapp/metadata-service/issues/7
https://github.com/kwizapp/poster-service/issues/17

**Comment by nikzaugg** [comment]
continue this issue in `kwiz-dotfiles`

closing this here
