### ISSUE TITLE
Github Demo Page

### ISSUE THREAD

**Issue by rschlaefli** [kwizapp/kwiz#51]
### Tasks
- [x] setup github pages repo
- [x] simple github pages with a demo
  - [x] there is only one page in fullscreen, which displays a [mobile device preview](https://marvelapp.github.io/devices.css/) in the middle
  - [x] the content of the mobile device preview shows our application within an iframe
